import type { Metadata } from "next";
import { JetBrains_Mono, Julius_Sans_One } from "next/font/google";
import Header from '@/components/Header';
import PageTransition from '@/components/PageTransition';
import "./globals.css";
import StairTransition from "@/components/StairTransition";


const JetBrainsMono = JetBrains_Mono({
  variable: "--font-jetBrainsMono",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
})

// const JuliusSansOne =
//   Julius_Sans_One({
//     variable: "--font-juliusSansOne",
//     subsets: ["latin"],
//     weight: ["400"],
//   });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const fontsVars = [
  JetBrainsMono,
  // JuliusSansOne
].map((font) => font.variable);

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${fontsVars.join(' ')} antialiased`}
      >
        <Header />
        <StairTransition />
        <PageTransition>
          { children }
        </PageTransition>
      </body>
    </html>
  );
}
